In [1]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# Entrada dataset
X = np.array([  [1,0,1]])

# Salidas dataset           
y = np.array([[1]])

# SIN BIAS
syn0=np.array([[0.2,-0.3],
[0.4,0.1],
[-0.5,0.2]])

syn1 =np.array([[-0.3],[-0.2]])

print(syn0)
print(syn1)

eta=0.9


[[ 0.2 -0.3]
 [ 0.4  0.1]
 [-0.5  0.2]]
[[-0.3]
 [-0.2]]


In [2]:
for iter in range(1):
      # Propagacion hacia adelante - desde capa 0 (entrada) a capa 1 a capa 2 (salida)
      neta1=np.dot(X,syn0)
      print('neta1:',neta1,'\n',)
      l1 = nonlin(neta1)
      print('salida intermedia l1:','\n',l1)
      neta2=np.dot(l1,syn1)
      print('neta2:','\n',neta2)
      l2 = nonlin(neta2)
      print('Salida red:','\n',l2)
  
      l2_error = y - l2

# ENTRENAMIENTO
      if (iter% 1000) == 0:
          print ('Error Promedio Absoluto:' + str(np.mean(np.abs(l2_error))))

      print('\n','***********empieza')
      l2_delta = l2_error * nonlin(l2,deriv=True)*eta
      print('l2delta',l2_delta)
      
      l1_error = l2_delta.dot(syn1.T)
      print('l1_error', l1_error)
      l1_delta = l1_error * nonlin(l1,deriv=True)*eta
      print('l1_delta',l1_delta)
      
	  # update weights
      syn1 += l1.T.dot(l2_delta)
      syn0 += X.T.dot(l1_delta)
        
print ('*********************************')
print ('Output After Training:')
print('Salida red:','\n',l2)
print ('Error:' + str(np.mean(np.abs(l2_error))),'\n')
print ('pesos: ')
print (syn1,'\n')
print (syn0,'\n')
# Con formateo
#print "%5d%10s" %(1,'a')

neta1: [[-0.3 -0.1]] 

salida intermedia l1: 
 [[0.42555748 0.47502081]]
neta2: 
 [[-0.22267141]]
Salida red: 
 [[0.44456103]]
Error Promedio Absoluto:0.5554389737704979

 ***********empieza
l2delta [[0.12343735]]
l1_error [[-0.03703121 -0.02468747]]
l1_delta [[-0.00814733 -0.00554082]]
*********************************
Output After Training:
Salida red: 
 [[0.44456103]]
Error:0.5554389737704979 

pesos: 
[[-0.24747031]
 [-0.14136469]] 

[[ 0.19185267 -0.30554082]
 [ 0.4         0.1       ]
 [-0.50814733  0.19445918]] 

