In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt 



Matplotlib is building the font cache; this may take a moment.


In [9]:
# Entrads en los patrones (dataset)
X = np.array([  [0,1,1],
                 [1,0,1],
                 [0,0,1],
                 [2,3,5],
                 [5,1,0],
                 [0,3,1] ])
# salidas en los patrones (dataset)           
y = np.array([[2,4,1,14,16,4]]).T

# semilla para random
np.random.seed(0)

# Inicialización de Pesos sinapticos
syn0 = np.array([[0.401],
                 [0.302],
                 [0.817] ])

In [10]:
print ('\n','Pesos Syn0','\n',syn0)


 Pesos Syn0 
 [[0.401]
 [0.302]
 [0.817]]


In [11]:
#Incrementar el numero de iteraciones, para entrenar ...352 iter

for iter in range(1):

        # forward propagation
        l0 = X
        neta=np.dot(l0,syn0)
        print('La neta es: ','\n',neta)

        # Funcion Sigmodea: 1/(1+exp(-neta) // Derivada de la Sigmoidea(x)  = x(1-x)
        
        l1 = 1/(1+np.exp(-neta))
        
        print('La salida es: ','\n',l1)

        # Cálculo del error
        l1_error = y - l1
        print('El error es: ','\n',l1_error)
        
        # Constante de aprendizaje eta  (entre 0 y 1) -- Que pasa si lo cambio?      
        eta=0.01
        
		# Cálculo del delta =(Error*eta*derivada de función)
		# Cálculo del delta  -  la Derivada, que para la función Sigmodea es x(1-x)
		
        derivada = l1 * (1-l1)
        l1_delta = l1_error * eta * derivada
        
        # Entrenamiento: Actualizacion de pesos
        syn0 += np.dot(l0.T,l1_delta)
        print('Los nuevos pesos son: ','\n',syn0)

La neta es:  
 [[1.119]
 [1.218]
 [0.817]
 [5.793]
 [2.307]
 [1.723]]
La salida es:  
 [[0.75380318]
 [0.7717114 ]
 [0.69359915]
 [0.99696045]
 [0.90945512]
 [0.84851485]]
El error es:  
 [[ 1.24619682]
 [ 3.2282886 ]
 [ 0.30640085]
 [13.00303955]
 [15.09054488]
 [ 3.15148515]]
Los nuevos pesos son:  
 [[0.46960812]
 [0.33007389]
 [0.83167228]]


In [12]:
print ('Salida despues del entrenamiento:')

print ('Patrones Entrada','\n', l0.T,'\n','Patrones Salida','\n',y,'\n','Salida Red','\n', l1,'\n','Error','\n',l1_error)
print ('\n','Pesos Syn0','\n',syn0)

Salida despues del entrenamiento:
Patrones Entrada 
 [[0 1 0 2 5 0]
 [1 0 0 3 1 3]
 [1 1 1 5 0 1]] 
 Patrones Salida 
 [[ 2]
 [ 4]
 [ 1]
 [14]
 [16]
 [ 4]] 
 Salida Red 
 [[0.75380318]
 [0.7717114 ]
 [0.69359915]
 [0.99696045]
 [0.90945512]
 [0.84851485]] 
 Error 
 [[ 1.24619682]
 [ 3.2282886 ]
 [ 0.30640085]
 [13.00303955]
 [15.09054488]
 [ 3.15148515]]

 Pesos Syn0 
 [[0.46960812]
 [0.33007389]
 [0.83167228]]
